version: '3'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    ports:
      - 8484:80
    environment:
      - DOMAIN=https://pw.zaratsyan.site
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=5
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$hX30NJT0SsCA/E+D5fgGsVKLAZHobGP7jsToOjAzWsA$$gjU8HehpmiHXhOIROg0JsGC4l3yWVI6AvddNenfSN4Q
