version: '2'

volumes:
  nextcloud:
  db:
  onlyoffice:

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - 8079:8079
    environment:
      - JWT_SECRET=secretjwtdontknowwhattoput
    volumes:
      - ./onlyoffice:/var/www/onlyoffice
